# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170420_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
