# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(default='Politics', editable=False),
        ),
    ]
